services:
  php:
    container_name: php_8.0_apache
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    links:
      - database
  database:
    image: mysql:8
    container_name: mysql_db
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=JtN83mLPC3